<template>
  <div class="entry-content">
    <p>
      <iframe
        loading="lazy"
        src="https://www.youtube.com/embed/KrhUczX_yg4"
        width="246"
        height="185"
        frameborder="0"
        allowfullscreen="allowfullscreen"
        >&amp;amp;lt;span data-mce-type=&#187;bookmark&#187;
        style=&#187;display: inline-block; width: 0px; overflow: hidden;
        line-height: 0;&#187;
        class=&#187;mce_SELRES_start&#187;&amp;amp;gt;&#xFEFF;&amp;amp;lt;/span&amp;amp;gt;</iframe
      >
      <iframe
        loading="lazy"
        src="https://www.youtube.com/embed/on38GM4b-_4"
        width="246"
        height="185"
        frameborder="0"
        allowfullscreen="allowfullscreen"
      ></iframe>
      <iframe
        loading="lazy"
        src="https://www.youtube.com/embed/noOQQyTNdqQ"
        width="246"
        height="185"
        frameborder="0"
        allowfullscreen="allowfullscreen"
      ></iframe>
      <iframe
        loading="lazy"
        src="https://www.youtube.com/embed/sIvNMxnO4oE"
        width="246"
        height="185"
        frameborder="0"
        allowfullscreen="allowfullscreen"
      ></iframe>
    </p>
    <p>
      <iframe
        loading="lazy"
        src="https://www.youtube.com/embed/YiSXCFSOcUY"
        width="246"
        height="185"
        frameborder="0"
        allowfullscreen="allowfullscreen"
      ></iframe>
      <iframe
        loading="lazy"
        src="https://www.youtube.com/embed/1SmFEC_-cGM"
        width="246"
        height="185"
        frameborder="0"
        allowfullscreen="allowfullscreen"
      ></iframe>
      <iframe
        loading="lazy"
        src="https://www.youtube.com/embed/TdrTBAv7XNM"
        width="246"
        height="185"
        frameborder="0"
        allowfullscreen="allowfullscreen"
      ></iframe>
      <iframe
        loading="lazy"
        src="https://www.youtube.com/embed/9298o3ZKHok"
        width="246"
        height="185"
        frameborder="0"
        allowfullscreen="allowfullscreen"
      ></iframe>
    </p>
    <p>
      <iframe
        loading="lazy"
        src="https://www.youtube.com/embed/g2LSeuHOk_U"
        width="246"
        height="185"
        frameborder="0"
        allowfullscreen="allowfullscreen"
      ></iframe>
      <iframe
        loading="lazy"
        src="https://www.youtube.com/embed/EMeZkAEMuNU"
        width="246"
        height="185"
        frameborder="0"
        allowfullscreen="allowfullscreen"
      ></iframe>
      <iframe
        loading="lazy"
        src="https://www.youtube.com/embed/BG73wd_xsZM"
        width="246"
        height="185"
        frameborder="0"
        allowfullscreen="allowfullscreen"
      ></iframe>
      <a
        href="https://www.fin-olimp.ru/wp-content/uploads/2018/12/Prezentatsiya_esse.pdf"
        >Презентация_эссе</a
      >
    </p>
    <p>
      <a
        href="https://www.fin-olimp.ru/wp-content/uploads/2019/04/Finansovaya-gramotnost.-Pervye-shagi-s-chego-nachat.pdf"
        >Финансовая грамотность. Первые шаги – с чего начать</a
      >
    </p>
    <p>
      <a
        href="https://www.fin-olimp.ru/wp-content/uploads/2019/04/S-dengami-na-Ty.-Zachem-byt-finansovo-gramotnym.pdf"
        >С деньгами на Ты. Зачем быть финансово грамотным</a
      >
    </p>
    <p>
      <a
        href="https://www.fin-olimp.ru/wp-content/uploads/2019/04/Osnovy-finansovoj-matematiki.pdf"
        >Основы финансовой математики</a
      >
    </p>
    <p>
      <iframe
        loading="lazy"
        src="https://www.youtube.com/embed/uIYMMODpdkQ"
        width="246"
        height="185"
        frameborder="0"
        allowfullscreen="allowfullscreen"
        >&amp;lt;span data-mce-type=&#187;bookmark&#187; style=&#187;display:
        inline-block; width: 0px; overflow: hidden; line-height: 0;&#187;
        class=&#187;mce_SELRES_start&#187;&amp;gt;&#xFEFF;&amp;lt;/span&amp;gt;</iframe
      >
    </p>
  </div>
</template>
